spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
          uri: lb://USERS-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 443
  
eureka:
  client:
    service-url:
      defaultZone: https://admintareas-production.up.railway.app/eureka/