spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service-route
          uri: lb://USERS-SERVICE


server:
  port: 443
  
eureka:
  client:
    service-url:
      defaultZone: https://admintareas-production.up.railway.app/eureka/