spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service-route
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 443
  
eureka:
  client:
    service-url:
      defaultZone: https://admintareas-production.up.railway.app/eureka/