spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
          uri: https://users-service-production-d729.up.railway.app/
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 443
  
eureka:
  client:
    service-url:
      defaultZone: https://admintareas-production.up.railway.app/eureka/