spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service-route
          uri: https://users-service-production-d729.up.railway.app/


server:
  port: 443
  
eureka:
  client:
    service-url:
      defaultZone: https://admintareas-production.up.railway.app/eureka/