spring:
  application:
    name: eureka-sv

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    lease-renewal-interval-in-seconds: 0
    hostname: admintareas-production.up.railway.app
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
    home-page-url: https://admintareas-production.up.railway.app/
    status-page-url: https://admintareas-production.up.railway.app/eureka/status
    health-check-url: https://admintareas-production.up.railway.app/eureka/health


