spring:
  application:
    name: notifications-service

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv.onrender.com/eureka/
  instance:
    hostname: notifications-service-plf6.onrender.com
    prefer-ip-address: false
    secure-port-enabled: true 
    secure-port: 443
    non-secure-port-enabled: false

mailtrap:
  api:
    token: ${PASSWORD_MAIL}
  sender: 
    email: hello@demomailtrap.com
    name: Notificaciones Administrador de Tareas
  