spring:
  application:
    name: notifications-service

  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: ${USER_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            checkserveridentity: false
            trust: live.smtp.mailtrap.io

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
