spring:
  application:
    name: tasks-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv.railway.internal:8761/eureka/
  instance:
    hostname: tasks-service.railway.internal
    prefer-ip-address: false
  
