spring:
  application:
    name: users-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv.onrender.com/eureka/
  instance:
    hostname: users-service-gew3.onrender.com
    prefer-ip-address: false
    secure-port-enabled: true 
    secure-port: 443
    non-secure-port-enabled: false

